services:
  unifi-os-server:
    image: ghcr.io/lemker/unifi-os-server:latest
    container_name: unifi-os-server
    privileged: true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - UOS_SYSTEM_IP=localhost
    volumes:
      - unifi-persistent:/persistent
      - unifi-data:/data
      - unifi-var-lib:/var/lib/unifi
      - unifi-mongodb:/var/lib/mongodb
    ports:
      - "11443:443"
      - "8080:8080"
      - "3478:3478/udp"
      - "10003:10003/udp"
    restart: unless-stopped

volumes:
  unifi-persistent:
  unifi-data:
  unifi-var-lib:
  unifi-mongodb:
