services:
  unifi-os-server:
    image: unifi-os-server:local
    container_name: unifi-os-server
    privileged: true
    volumes:
      - unifi-persistent:/persistent
      - unifi-data:/data
      - unifi-var-lib:/var/lib/unifi
      - unifi-mongodb:/var/lib/mongodb
    ports:
      - "11443:443"
      - "8080:8080"
      - "3478:3478/udp"
      - "10003:10003/udp"
    restart: unless-stopped

volumes:
  unifi-persistent:
  unifi-data:
  unifi-var-lib:
  unifi-mongodb:
